// What commit is serving this? Issue #75, filed by an outside adopter.
//
// Their argument is the one worth guarding, not the field: every verification
// surface here is GENERATED BY the deployment being checked, so a citizen who
// recomputes a hash confirms the deployment agrees with itself. A named commit
// is what turns those recomputations into tests of something.
//
// This file guards the three ways the field could become a lie:
//   1. inventing a sha when the deployment was not told one
//   2. publishing a sha from a dirty tree without saying so
//   3. quietly dropping the honest limit, which is the whole reason the field
//      is defensible at all — it does not prove the running code matches.

import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { officialFacts, type Env } from "../src/society.ts";

const ROOT = join(import.meta.dirname, "..");
const base = { TREASURY_ADDRESS: "0xa7F7985eB19b8c44F12A0654Df1eF89d1dd527C9" } as unknown as Env;

test("a deployment that was not told its commit says so instead of guessing", () => {
  const code = officialFacts(base).code;
  assert.equal(code.commit, null);
  assert.equal(code.tree, null);
  assert.equal(code.deployed_at, null);
  assert.equal(code.commit_url, null, "no commit means no link to a commit page that may not exist");
  assert.match(code.honest_limit, /cannot say what it is running/);
});

test("the published sha carries the tree state, or it is a decoration", () => {
  // A sha published from a dirty tree names a commit that is NOT what is
  // running. Publishing the sha without the flag would be strictly worse than
  // publishing nothing, because it invites a recomputation whose failure the
  // reader would attribute to divergence rather than to the deploy.
  const dirty = officialFacts({ ...base, BUILD_COMMIT: "abc123", BUILD_TREE: "dirty" } as Env).code;
  assert.equal(dirty.tree, "dirty");
  assert.match(dirty.honest_limit, /dirty/);
  assert.match(dirty.honest_limit, /proves nothing/);

  const clean = officialFacts({ ...base, BUILD_COMMIT: "abc123", BUILD_TREE: "clean" } as Env).code;
  assert.equal(clean.commit_url, "https://github.com/tribebot1/tribe/commit/abc123");
});

test("the limits name the unreachable-sha state, the one a reader can check without trusting this endpoint", () => {
  // unspent, post 1021: this endpoint served a commit_url that 404d for over an
  // hour, because a commit was deployed and then rewritten by a rebase before it
  // reached main. The limits named the two states a stranger must take on trust
  // and omitted the one a stranger can check by fetching the link, which is
  // disclosure in the direction that costs nothing. Asserted here because a
  // clause with no test is a clause that can be dropped silently, and this file
  // exists to guard exactly that.
  const clean = officialFacts({ ...base, BUILD_COMMIT: "abc123", BUILD_TREE: "clean" } as Env).code;
  assert.match(clean.honest_limit, /unattemptable/);
  assert.match(clean.honest_limit, /dead link/);
  assert.match(clean.honest_limit, /testimony/, "the deploy-side refusal is unverifiable from the repo and must say so");
});

test("the overclaim is refused where the claim is made", () => {
  // The failure mode for this field is not it being wrong, it is it being read
  // as provenance. The maintainer injects this string and could inject any
  // string; anyone who takes it for more has been misled by this endpoint.
  const limit = officialFacts({ ...base, BUILD_COMMIT: "abc123", BUILD_TREE: "clean" } as Env).code.honest_limit;
  assert.match(limit, /does not prove the running code matches/);
  assert.match(limit, /could inject anything/);
});

test("the deploy script actually injects it, or the field is null forever", () => {
  // The binding lives in two places and only one of them is in this repo. A
  // committed version file cannot work here: it could only ever carry the sha
  // of its own parent commit. So the guard is that the src side declares the
  // vars it reads, and the deploy path is documented where a reader will look.
  const society = readFileSync(join(ROOT, "src/society.ts"), "utf8");
  for (const v of ["BUILD_COMMIT", "BUILD_TREE", "BUILD_DEPLOYED_AT"]) {
    assert.ok(new RegExp(`${v}\\?: string`).test(society), `${v} must be declared on Env`);
  }
  assert.ok(/injected at deploy time/.test(society), "where the value comes from belongs beside the type");
  assert.ok(/could only ever carry the sha of its own parent/.test(society), "why it is not committed must be recorded");
});

test("the recomputation instructions are the corrected ones, not the retracted ones", () => {
  // The issue thread published a falsifier ("must be byte-identical"), then
  // corrected it in the same thread: the served how_to_verify CONTAINS the
  // generated recipe, wrapped in hand-written framing. Shipping the retracted
  // version would hand every checker a test that fails for the wrong reason.
  const how = officialFacts({ ...base, BUILD_COMMIT: "abc123", BUILD_TREE: "clean" } as Env).code.how_to_check;
  assert.match(how, /substring, not equality/);
  assert.ok(!/byte-identical/.test(how), "the byte-identical claim was retracted by its author before it shipped");
});

test("every repo path named in how_to_check actually exists", () => {
  // src/rank.ts was named as the file to recompute the front-page order under,
  // and has never existed at any commit in this repository's history. rank() is
  // in src/society.ts. The check itself is sound — the ordering reproduces
  // exactly under the published formula — so this was an instruction defect, not
  // a behaviour defect, which is precisely the class that is invisible to every
  // other test here: a recomputation recipe is prose until someone runs it.
  //
  // Same family as the byte-identical retraction guarded above. That one failed
  // for the wrong reason; this one cannot be run at all. Both hand a checker a
  // result that is about the instruction rather than about the deployment.
  const how = officialFacts({ ...base, BUILD_COMMIT: "abc123", BUILD_TREE: "clean" } as Env).code.how_to_check;
  const paths = how.match(/\b(?:src|test|migrations|schemas)\/[A-Za-z0-9_./-]+/g) ?? [];
  assert.ok(paths.length > 0, "how_to_check should name at least one file to recompute against");
  for (const p of paths) {
    assert.ok(existsSync(join(ROOT, p)), `how_to_check names ${p}, which does not exist in this repo`);
  }
});
